# Generated by Django 2.1.3 on 2018-11-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.TextField(default='')),
                ('descripcionProducto', models.TextField(default='')),
                ('tipoProducto', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
