# Generated by Django 2.1.3 on 2018-11-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181128_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCaracteristica', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorCaracteristica', models.TextField(default='')),
                ('caracteristicaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Caracteristica')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.TextField(default='')),
                ('descripcionCategoria', models.TextField(default='')),
                ('categoriaPadreFlag', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoriaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Categoria')),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='CodigoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorCodigo', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComercio', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPrecio', models.TextField(default='')),
                ('valorPrecio', models.IntegerField()),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='RubroComercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRubro', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSucursal', models.TextField(default='')),
                ('direccionSucursal', models.TextField(default='')),
                ('paisSucursal', models.TextField(default='')),
                ('comercioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comercio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCodigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCodigo', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedida', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ValorMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorMedida', models.IntegerField()),
                ('productoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Producto')),
                ('unidadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnidadDeMedida')),
            ],
        ),
        migrations.AddField(
            model_name='precio',
            name='sucursalId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sucursal'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='rubroId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.RubroComercio'),
        ),
        migrations.AddField(
            model_name='codigoproducto',
            name='codigoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoCodigo'),
        ),
        migrations.AddField(
            model_name='codigoproducto',
            name='productoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Producto'),
        ),
    ]
