# Generated by Django 2.1.3 on 2018-12-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181130_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valormedida',
            name='valorMedida',
        ),
        migrations.AddField(
            model_name='valormedida',
            name='valorUnidadMedida',
            field=models.TextField(default=''),
        ),
    ]
