# Generated by Django 2.1.3 on 2018-12-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181202_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='valorPrecio',
            field=models.TextField(default=''),
        ),
    ]
